Created about section
NgachaIan/PersonalPortfolio pull request #2
Opened 2023-04-28 19:36 UTC by NgachaIan

Finish about section and entire web app

2023-04-28 21:13 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @NgachaIan, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 21:13 UTC, Qoosim commented on index.html
> +                <img class="frame" src="img/Frame.png">
- [ ] If the image is not part of the page content, it should be added via background-image css property. That is what happens here too. Decorations are always backgrounded images, not img tags. Kindly add this background image with css background-image property.

2023-04-28 21:13 UTC, Qoosim commented on index.html
> +                    <img class="icon-language" src="img/icon-frameworks.png">
- [ ] If the image is not part of the page content, it should be added via background-image css property. That is what happens here too. Decorations are always backgrounded images, not img tags. Kindly add this background image with css background-image property.

2023-04-28 21:13 UTC, Qoosim commented on index.html
> +                </div>
- [ ] Kindly remove the dark border on the `See project` button so as to match the Figma design.

### Your Design
![your-design](https://user-images.githubusercontent.com/26597432/235254843-22ea0648-f19c-4172-b5c0-2222c36461b9.png)

### Figma Design
![temp-design](https://user-images.githubusercontent.com/26597432/235254871-d9d407fc-530c-4d9a-bdf5-e92bee008d3e.png)

2023-04-29 13:06 UTC, emmiiorji approved these changes
Hi @NgachaIan, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/235302769-ce229a42-ec41-4bed-b1ad-6ff4b9baed38.gif'/>
</div>


## Good Highlights✔️

- Requested changes have been implemented

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 13:16 UTC, merged